# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

jdk:
- openjdk11

services:
- postgresql

before_install:
  - psql -c 'create database cinema;' -U postgres
  - psql -c 'create database servlet;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="e9acd711-6257-48ee-92fb-d6a448d5c388"

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка   упала
notifications:
  email:
    recipients:
      - telesyn73@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
